#!/usr/bin/env python
"""
Create word fingerprints from CSV dumps of the comments table of a
Wordpress site.
"""

import csv
import sys

def usage():
    print "usage: %s CSV ..." % (sys.argv[0])
    sys.exit(0)

def read_comments():
    pass

def generate_wordprint(comments_csv):
    pass

if __name__ == '__main__':
    if len(sys.argv) == 1:
        usage()

    for comments_csv in sys.argv[1:]:
        generate_wordprint(comments_csv)
